version: '2'

services:
  authen:
    build:
      context: ./docker
      args:
        - INSTALL_SSH=false
        - INSTALL_APACHE_PHP=true
        - INSTALL_XDEBUG=true
    environment:
      PHP_XDEBUG_ENABLED: 1
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "docker-host:172.16.0.1"
    ports:
      - "8080:80"
    networks:
      mynet:
        ipv4_address: 172.16.0.10
    volumes:
      - "./source:/var/www/html"
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
